### PR TITLE
Add optional safeTxGas feature

### PR DESCRIPTION
**Pull request by iamacook**
To match the new feature in the chains endpoint the `FEATURES` enum was extended to add `SAFE_TX_GAS_OPTIONAL`.

### CODE REVIEW

**Review by katspaugh — APPROVED** [review]
Thanks 👍

**Review by katspaugh — CHANGES_REQUESTED** [review]
Wait

**Comment by iamacook** [comment]
Why is this then alongside the same details that are to be returned from the endpoint?

**Comment by katspaugh** [comment]
Reopened because we still need to define this feature in the enum.

**Review by katspaugh — APPROVED** [review]

**Pull request merged**
